# general configuration
url: ''
baseurl: ''

# personal configuration
owner:
  author: Rodrigo C. G. Pena # name under the avatar
  description: Personal Website
  email:
    handle: rodrigocgp
    provider: gmail.com
  include_analytics: false # include analytics.html at the end of <head>
  include_landing: true # generate landing page
  logo: /images/me.png # (optional) an avatar or logo
  tagline: Researcher # (optional) tagline under the title

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# dependencies
markdown: kramdown
highlighter: rouge

# permalinks
permalink: pretty
