# general configuration
url: '' # base hostname & protocol of the site, e.g. http://example.com
baseurl: ''
reading_time: true
words_per_minute: 200
excerpt_separator: "<!--more-->"

# personal configuration
owner:
  author: Rodrigo C. G. Pena # name under the avatar
  description: Personal Website
  email:
    handle: rodrigocgp
    provider: gmail.com
  include_analytics: false # include analytics.html at the end of <head>
  include_landing: true # generate landing page
  logo: /images/me.png # (optional) an avatar or logo
  tagline: Researcher # (optional) tagline under the title

# analytics
google_analytics: UA-115358555-1  # Analytics Property ID
google_verify: Z1RJE6QhVYyI4ypHTDgE1oOIt_VPwNrwgxUK7wv1f38  # Webmaster

# tz database name http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Zurich

# dependencies
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-paginate

permalink: /:year/:month/:title
paginate: 5
paginate_path: "blog/page:num/"

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]